branches:
  only:
  - master

language: node_js
node_js:
  - 'node'

os:
  - windows
  - osx
  - linux

install:
  - npm install

script:
  - npm run lint
  - ./publish.sh

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: ./dist/*.txt
  skip_cleanup: true
  on:
    tags: true
